# Generated by Django 6.0.3 on 2026-03-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('Job Seeker', 'Job Seeker')], default='Job Seeker', max_length=20),
        ),
    ]
